### ISSUE TITLE
windows terminal error on launch

### ISSUE THREAD

**Issue by jianghao08** [wkgcass/jdkman#1]
![微信截图_20240410173246](https://github.com/wkgcass/jdkman/assets/28949366/e21bfa3e-0008-4a19-bc72-62606b6d189e)

**Comment by wkgcass** [comment]
Please use `1.0.0` for now. The `1.0.1` is buggy, I'll fix it later

**Comment by jianghao08** [comment]
> Please use `1.0.0` for now. The `1.0.1` is buggy, I'll fix it later

OK, thans for reply

**Comment by wkgcass** [comment]
@jianghao08 You can try the latest `1.0.2` now

**Comment by jianghao08** [comment]
@wkgcass I tried, it looks great.
